baseURL = "http://localhost:1313"
title = "Bold Explorers"
theme = "universal"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
canonifyURLs = true

# Parámetros Principales
[params]
   style = "default"
   logo = "img/logo.png"
   logo_small = "img/logo-small.png"
   custom_css = ["css/custom.css"]
   mainColor = "#0d3b66"
   backgroundColor = "#f5f5f7"
   author = "Bold Explorers"
   defaultKeywords = ["travel", "family", "adventure", "national parks"]
   defaultDescription = "Family adventure travel guides and experiences"
   date_format = "July 19, 2011"
   carousel_enable = true
   js = ["jquery","bootstrap","owl.carousel","front"]

   [params.CarouselHomepage]
       enable = true
       auto_play = true
       slide_speed = 2000
       pagination_speed = 1000
       
   [params.features]
       enable = true
   
   [params.see_more]
       enable = true
       
   [params.recent_posts]
       enable = true
       title = "Recent Posts"
       subtitle = "Check our latest posts"

   [params.widgets]
       enable = true
       search = true
       categories = true
       tags = true

   # Selector de idioma
   [params.language_chooser]
       enable = true
       show_flags = true

# Configuración de Idiomas
[languages]
   [languages.en]
       languageCode = "en-us"
       contentDir = "content/en"
       weight = 1
       title = "Bold Explorers"
       languageName = "English"
       
    [languages.en.params]
        mainSections = ["blog", "destinations", "guides", "itineraries", "tips"]

       [languages.en.permalinks]
           blog = "/blog/:sections[1:]/:slug/"
           destinations = "/destinations/:sections[1:]/:slug/"
           guides = "/guides/:slug/"
           itineraries = "/itineraries/:slug/"
           tips = "/tips/:slug/"
       
       [[languages.en.menu.main]]
           identifier = "blog"
           name = "Blog"
           url = "/blog/"
           weight = 1
       [[languages.en.menu.main]]
           identifier = "destinations"
           name = "Destinations"
           url = "/destinations/"
           weight = 2
       [[languages.en.menu.main]]
           identifier = "guides"
           name = "Guides"
           url = "/guides/"
           weight = 3
       [[languages.en.menu.main]]
           identifier = "itineraries"
           name = "Itineraries"
           url = "/itineraries/"
           weight = 4
       [[languages.en.menu.main]]
           identifier = "tips"
           name = "Travel Tips"
           url = "/tips/"
           weight = 5

   [languages.es]
       languageCode = "es"
       contentDir = "content/es"
       weight = 2
       title = "Bold Explorers"
       languageName = "Español"

       [languages.es.params]
        mainSections = ["blog", "destinos", "guias", "itinerarios", "consejos"]
       
       [languages.es.permalinks]
           blog = "/blog/:sections[1:]/:slug/"
           destinos = "/destinos/:sections[1:]/:slug/"
           guias = "/guias/:slug/"
           itinerarios = "/itinerarios/:slug/"
           consejos = "/consejos/:slug/"
       
       [[languages.es.menu.main]]
           identifier = "blog"
           name = "Blog"
           url = "/blog/"
           weight = 1
       [[languages.es.menu.main]]
           identifier = "destinos"
           name = "Destinos"
           url = "/destinos/"
           weight = 2
       [[languages.es.menu.main]]
           identifier = "guias"
           name = "Guías"
           url = "/guias/"
           weight = 3
       [[languages.es.menu.main]]
           identifier = "itinerarios"
           name = "Itinerarios"
           url = "/itinerarios/"
           weight = 4
       [[languages.es.menu.main]]
           identifier = "consejos"
           name = "Consejos"
           url = "/consejos/"
           weight = 5

# Taxonomías
[taxonomies]
   # Tipos de Contenido
   category = "categories"  # blog, guide, destination, itinerary, tip
   
   # Ubicación
   continent = "continents"
   country = "countries"
   
   # Características del Viaje
   travel = "travel"
   activity = "activities"
   season = "seasons"
   difficulty = "difficulties"
   
   # Planificación
   planning = "planning"
   duration = "duration"
   budget = "budget"
   
   # General
   tag = "tags"

# Configuración del renderizado de Markdown
[markup]
   [markup.goldmark]
       [markup.goldmark.renderer]
           unsafe = true

   [markup.highlight]
       style = "monokai"
       tabWidth = 4

# Configuración de Outputs
[outputs]
   home = ["HTML", "RSS"]
   section = ["HTML"]
   taxonomy = ["HTML"]
   term = ["HTML"]

# Privacy Configuration
[privacy]
   [privacy.disqus]
       disable = true
   [privacy.googleAnalytics]
       anonymizeIP = true
       disable = false
       respectDoNotTrack = true
       useSessionStorage = true
   [privacy.instagram]
       disable = false
       simple = true
   [privacy.twitter]
       disable = false
       enableDNT = true
       simple = true
   [privacy.vimeo]
       disable = false
       simple = true
   [privacy.youtube]
       disable = false
       privacyEnhanced = true

[module]
   [[module.mounts]]
       source = "assets"
       target = "assets"